# Common reusable workflow for create-related events.
on:
  workflow_call: {}
jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch' && github.ref_name != 'main' && github.ref_name != 'master' && github.ref_name != 'dev' && !startsWith('dependabot/', github.ref_name) && !startsWith('revert-', github.ref_name)
    steps:
      - id: extract-issue-key
        name: Extract issue key
        uses: solvocloud/action-extract-jira-key@1.1
        with:
          input: ${{ github.ref_name }}
      - id: validate-branch-name
        name: Validate branch name
        uses: solvocloud/action-validate-jira-key@1.1
        with:
          key: ${{ steps.extract-issue-key.outputs.issue-key }}
          jiraUrl: ${{ secrets.JIRA_URL }}
          jiraEmail: ${{ secrets.JIRA_EMAIL }}
          jiraApiToken: ${{ secrets.JIRA_API_TOKEN }}
