on:
  workflow_call: {}
jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    # Don't run this step if the PR is either from dev, or to main (or both).
    if: github.base_ref != 'main' || github.head_ref != 'dev'
    steps:
      - name: validate-pr-title
        uses: solvocloud/action-pr-title@1.0
        with:
          prTitle: ${{ github.event.pull_request.title }}
          jiraUrl: ${{ secrets.JIRA_URL }}
          jiraEmail: ${{ secrets.JIRA_EMAIL }}
          jiraApiToken: ${{ secrets.JIRA_API_TOKEN }}
