# Common reusable workflow for PR-related events.
# A reference to this workflow should be made by other repositories, in workflows that
# deal with pull requests (i.e. having "on" -> "pull_request" in their header).
#
# The idea is to have this common workflow contain whatever jobs and steps needed for all
# PR-related events.
on:
  workflow_call: {}
jobs:
  validate-jira-issue-key:
    runs-on: ubuntu-latest
    # Don't run this step if the PR is either from dev, or to main/master (or both).
    if: (github.base_ref != 'main' && github.base_ref != 'master') || github.head_ref != 'dev'
    steps:
      - id: extract-issue-key-from-pr
        name: Extract issue key from PR title
        uses: solvocloud/action-extract-jira-key@1.1
        with:
          input: ${{ github.event.pull_request.title }}
      - id: extract-issue-key-from-branch
        name: Extract issue key from branch name
        uses: solvocloud/action-extract-jira-key@1.1
        with:
          input: ${{ github.head_ref }}
      - id: validate-pr-title
        name: Validate PR title
        uses: solvocloud/action-validate-jira-key@1.1
        with:
          key: ${{ steps.extract-issue-key-from-pr.outputs.issue-key }}
          jiraUrl: ${{ secrets.JIRA_URL }}
          jiraEmail: ${{ secrets.JIRA_EMAIL }}
          jiraApiToken: ${{ secrets.JIRA_API_TOKEN }}
      - id: validate-branch-name
        name: Validate branch name
        uses: solvocloud/action-validate-jira-key@1.1
        with:
          key: ${{ steps.extract-issue-key-from-branch.outputs.issue-key }}
          jiraUrl: ${{ secrets.JIRA_URL }}
          jiraEmail: ${{ secrets.JIRA_EMAIL }}
          jiraApiToken: ${{ secrets.JIRA_API_TOKEN }}
# Comment this out for now. This fails because we need to connect to CodeArtifact for the purpose
# of downloading third-party libraries, specifically solvo-lib. That requires an IAM user to be created.
# We'll do this soon.
#
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - id: checkout
#        name: Clone repository
#        uses: actions/checkout@v3
#      - id: setup-python
#        name: Setup Python environment
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.8'
#      - id: unit-tests
#        name: Run unit tests
#        run: |
#          python -m venv .venv
#          source .venv/bin/activate
#          pip install pytest
#          pip install -e .
#          if [ -f test-requirements.txt ]; then
#            pip install -r test-requirements.txt
#          fi
#          pytest
