on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
      codebuild_project_name:
        required: false
        type: string
        default: ""
jobs:
  check-automated-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Connect to AWS github identity provider
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ORG_GITHUB_ENTRY_ROOT_ACCOUNT_ROLE_ARN }}
          role-session-name: ${{ inputs.module_name }}-org
          aws-region: ${{ vars.AWS_REGION }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_GITHUB_ROLE }}
          role-session-name: ${{ inputs.module_name }}-module
          role-chaining: true
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: solvocloud/github-workflows
      - name: Check automated tests
        run: .github/scripts/check-automated-tests.sh ${{ inputs.module_name }} ${{ github.event.pull_request.head.sha }} ${{ vars.AWS_ARTIFACTS_BUCKET_NAME }} ${{ inputs.codebuild_project_name }}
        shell: bash
