on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
jobs:
  check-automated-tests:
    runs-on: ubuntu-latest
    if: "github.ref_type == 'branch' && github.base_ref == 'main'"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_GITHUB_ROLE }}
          role-session-name: ${{ inputs.module_name }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check automated tests
        run: .github/scripts/check-automated-tests.sh ${{ inputs.module_name }} ${{ github.event.pull_request.head.sha }} ${{ vars.AWS_ARTIFACTS_BUCKET_NAME }}
        shell: bash
