on:
  workflow_call: {}
jobs:
  transition-jira-issues:
    # Only run if the PR is actually merged, and into "main".
    if: "github.event.pull_request.merged == true && github.base_ref == 'main'"
    runs-on: ubuntu-latest
    name: Transition JIRA issues
    steps:
      - id: transition-jira-issues
        name: Transition JIRA issues
        uses: solvocloud/action-transition-jira-issues@1.0
        with:
          payload_string: ${{ toJson(github.event) }}
          # Within the "SOLVO" JIRA project, this is the transition ID that takes issues into "Prod" status.
          transition_id: 51
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      JIRA_URL: ${{ vars.JIRA_URL }}
      JIRA_EMAIL: ${{ vars.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
